config/routes.rb
Bulimia::Application.routes.draw do
  
  root :to => 'application#home_page'
  
  resources :physicians do
    resources :patients do
      resources :log_entries
    end
  end
  
  match 'physician_signup_part2/:id(.:format)' => 'physicians#signup_part2', :as => "physician_signup_part2"
  match "home_page" => "application#home_page", :as => "home_page"
  match "deactivate_pt_msg/:physician_id/:patient_id" => "physicians#deactivate_pt_message", :as => "deactivate_pt_message"
  match "deactivate_ph_msg/:physician_id" => "physicians#deactivate_ph_message", :as => "deactivate_ph_message"
  match "ph_deactivate" => "physicians#destroy_archive", :as => "destroy_archive"
  match "pt_archive/:physician_id/:id" => "patients#archive", :as => "archive_pt"
  match "physician/:physician_id/patient_archive" => "physicians#pt_archive_index", :as => "pt_archive_index"
  match "code" => "sessions#new_patient_code_verification", :as => "patient_code"
  match "new_patient" => "sessions#new_patient_start_code_entry", :as => "new_patient_start_code_entry"
  match "new_patient_password_setup/:pt_id" => "sessions#new_patient_password_setup", :as => "new_patient_password_setup"
  match "p_set/:pt_id" => "sessions#password_set", :as => "password_set"
  
  
  
  match 'phone/sms_handler' => "phone#sms_handler", :as => "sms_handler"
  match 'after_start_code_web_handler' => "patients#after_start_code_web_handler", :as => "after_start_code_web_handler"
  
  match "physician_log_out" => "sessions#destroy_ph", :as => "log_out"
  match "physician_log_in" => "sessions#new_physician_session", :as => "log_in"
  match "physician_find" => "sessions#create_ph_session", :as => "matched"
  match "physician_sign_up" => "physicians#new", :as => "sign_up"
  match "physician_additional_info" => "physicians#physician_additional_info", :as => "physician_additional_info"
  match "welcome_ph_instructions/:physician_id" => "physicians#welcome_ph_instructions", :as => "welcome_ph_instructions" 
  match "unarch_pt/:id/:patient_id" => "physicians#unarchive_patient", :as => "unarchive_patient"
  match "physician_account/:physician_id" => "physicians#physician_account", :as => "physician_account"
  match "edit_physician_account/:physician_id" => "physicians#edit_physician_account", :as => "edit_physician_account"
  match "physician_pswd_edit/:physician_id" => "physicians#ph_password_edit", :as => 'ph_password_edit'
  match "physician_pswd_update/:physician_id" => "physicians#ph_password_update", :as => 'ph_password_update'
  
  
  match "patient_log_out" => "sessions#destroy_pt", :as => "patient_log_out"
  match "patient_log_in" => "sessions#new_patient_session", :as => "patient_log_in"
  match "patient_find" => "sessions#create_pt_session", :as => "patient_matched"
  match "patient_edit/:patient_id" => "patients#patient_edit_limited", :as => "pt_edit"
  match "patient_show/:patient_id" => "patients#patient_show_limited", :as => "pt_show"
  match "patient_update/:patient_id" => "patients#patient_update_limited", :as => "pt_update"
  match "patient_welcome/:patient_id" => "patients#patient_welcome", :as => "patient_welcome"
  
  
  match "admin_override_pt_password_edit/:patient_id" => "patients#admin_pt_password_edit", :as => "admin_pt_pass_edit"
  match "admin_override_pt_password_update/:patient_id" => "patients#admin_pt_password_update", :as => "admin_pt_pass_update"
  match "admin" => "admin#index", :as => "admin"
  match "archived_physicians" => "admin#archived_physicians", :as => "archived_physicians"
  match "archived_patients" => "admin#archived_patients", :as => "archived_patients"
  match "active_patients" => "admin#active_patients", :as => "active_patients"
  match "deact_and_arch_pt/:patient_id" => "admin#deactivate_and_archive_patient", :as => "deactivate_and_archive_patient"
  match "react_and_unarch_pt/:patient_id" => "admin#reactivate_and_unarchive_patient", :as => "reactivate_and_unarchive_patient"
  match "archive_a_physician/:physician_id" => "admin#archive_a_physician", :as => "archive_a_physician"
  match "unarchive_a_physician/:physician_id" => "admin#unarchive_a_physician", :as => "unarchive_a_physician"
  

    
  

end

app/views/admin/active_patients.html.erb
<h1>Active Patient Accounts</h1>

<% @patients_act.each do |pt| %>
	</br><%= pt.phone_number %>, Patient ID: <%= pt.id %>, Physician: <%= Physician.find(pt.physician_id).email %> <%= link_to "Deactivate and Archive", deactivate_and_archive_patient_path(:patient_id => pt.id) %></br>
	<% end %>

app/views/admin/archived_patients.html.erb
<h1>Archived Patient Accounts</h1>

<% @patients_arch.each do |pt| %>
	</br><%= pt.phone_number %>, Patient ID: <%= pt.id %>, , Physician: <%= Physician.find(pt.physician_id).email %> <%= link_to "Reactivate and Unarchive", reactivate_and_unarchive_patient_path(:patient_id => pt.id) %></br>
	<% end %>

app/views/admin/archived_physicians.html.erb
<h1>Archived Physician Accounts</h1>

	<% @physicians_archive.each do |ph| %>
		</br><%= ph.email %>  Archive ID: <%= ph.arch_id %>   <%= link_to "View Patients", physician_patients_path(ph) %>   ||  <%= link_to "Unarchive this Physician", unarchive_a_physician_path(:physician_id => ph.id) %> </br>
		<% end %>

app/views/admin/index.html.erb
<h1>ADMIN HOME</h1></br></br>


<%= link_to "View Archived Physicians", archived_physicians_path %></br>
<%= link_to "View Archived Patients", archived_patients_path %></br>
<%= link_to "View Active Patients", active_patients_path %></br></br></br>
<h2>List of Physicians by email:</h2></br>
<% @physicians.each do |ph| %>
	</br><%= ph.email %>    <%= link_to "View Patients", physician_patients_path(ph) %>   ||  <%= link_to "Archive this Physician", archive_a_physician_path(:physician_id => ph.id) %> </br>
	<% end %>
	
	