config/routes.rb
Bulimia::Application.routes.draw do
  
  root :to => 'application#home_page'
  
  resources :physicians do
    resources :patients do
      resources :log_entries
    end
  end
  
  match 'physician_signup_part2/:id(.:format)' => 'physicians#signup_part2', :as => "physician_signup_part2"
  match "home_page" => "application#home_page", :as => "home_page"
  match "deactivate_pt_msg/:physician_id/:patient_id" => "physicians#deactivate_pt_message", :as => "deactivate_pt_message"
  match "deactivate_ph_msg/:physician_id" => "physicians#deactivate_ph_message", :as => "deactivate_ph_message"
  match "ph_deactivate" => "physicians#destroy_archive", :as => "destroy_archive"
  match "pt_archive/:physician_id/:id" => "patients#archive", :as => "archive_pt"
  match "physician/:physician_id/patient_archive" => "physicians#pt_archive_index", :as => "pt_archive_index"
  match "code" => "sessions#new_patient_code_verification", :as => "patient_code"
  match "new_patient" => "sessions#new_patient_start_code_entry", :as => "new_patient_start_code_entry"
  match "new_patient_password_setup/:pt_id" => "sessions#new_patient_password_setup", :as => "new_patient_password_setup"
  match "p_set/:pt_id" => "sessions#password_set", :as => "password_set"
  
  
  
  match 'phone/sms_handler' => "phone#sms_handler", :as => "sms_handler"
  match 'after_start_code_web_handler' => "patients#after_start_code_web_handler", :as => "after_start_code_web_handler"
  
  match "physician_log_out" => "sessions#destroy_ph", :as => "log_out"
  match "physician_log_in" => "sessions#new_physician_session", :as => "log_in"
  match "physician_find" => "sessions#create_ph_session", :as => "matched"
  match "physician_sign_up" => "physicians#new", :as => "sign_up"
  match "physician_additional_info" => "physicians#physician_additional_info", :as => "physician_additional_info"
  match "welcome_ph_instructions/:physician_id" => "physicians#welcome_ph_instructions", :as => "welcome_ph_instructions" 
  match "unarch_pt/:id/:patient_id" => "physicians#unarchive_patient", :as => "unarchive_patient"
  match "physician_account/:physician_id" => "physicians#physician_account", :as => "physician_account"
  match "edit_physician_account/:physician_id" => "physicians#edit_physician_account", :as => "edit_physician_account"
  match "physician_pswd_edit/:physician_id" => "physicians#ph_password_edit", :as => 'ph_password_edit'
  match "physician_pswd_update/:physician_id" => "physicians#ph_password_update", :as => 'ph_password_update'
  
  
  match "patient_log_out" => "sessions#destroy_pt", :as => "patient_log_out"
  match "patient_log_in" => "sessions#new_patient_session", :as => "patient_log_in"
  match "patient_find" => "sessions#create_pt_session", :as => "patient_matched"
  match "patient_edit/:patient_id" => "patients#patient_edit_limited", :as => "pt_edit"
  match "patient_show/:patient_id" => "patients#patient_show_limited", :as => "pt_show"
  match "patient_update/:patient_id" => "patients#patient_update_limited", :as => "pt_update"
  match "patient_welcome/:patient_id" => "patients#patient_welcome", :as => "patient_welcome"
  
  
  match "admin_override_pt_password_edit/:patient_id" => "patients#admin_pt_password_edit", :as => "admin_pt_pass_edit"
  match "admin_override_pt_password_update/:patient_id" => "patients#admin_pt_password_update", :as => "admin_pt_pass_update"
  match "admin" => "admin#index", :as => "admin"
  match "archived_physicians" => "admin#archived_physicians", :as => "archived_physicians"
  match "archived_patients" => "admin#archived_patients", :as => "archived_patients"
  match "active_patients" => "admin#active_patients", :as => "active_patients"
  match "deact_and_arch_pt/:patient_id" => "admin#deactivate_and_archive_patient", :as => "deactivate_and_archive_patient"
  match "react_and_unarch_pt/:patient_id" => "admin#reactivate_and_unarchive_patient", :as => "reactivate_and_unarchive_patient"
  match "archive_a_physician/:physician_id" => "admin#archive_a_physician", :as => "archive_a_physician"
  match "unarchive_a_physician/:physician_id" => "admin#unarchive_a_physician", :as => "unarchive_a_physician"
  

    
  

end

app/models/physician.rb
class Physician < ActiveRecord::Base
    attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :state, :specialty, :arch_id, :archive
    has_secure_password
    
    validates_presence_of :first_name, :last_name, :state, :specialty, :on => :update
    validates_presence_of :password, :on => :create
    validates_length_of :password, :minimum => 6, :allow_blank => false, :on => :create
    validates_confirmation_of :password, :on => :create 
    validates_presence_of :email
    validates_uniqueness_of :email
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    
    has_many :patients
    
    # validates_presence_of :password, :if => :should_validate_password?
    # validates_presence_of :country
    # validates_presence_of :state, :if => :in_us?
    # attr_accessor :updating_password

    # def in_us?
    #   country == 'US'
    # end

    # def should_validate_password?
    #   updating_password || new_record?
    # end

    # # in controller
    # @user.updating_password = true
    # @user.save
    
    
    def full_name
      self.first_name + " " + self.last_name
    end
    
    
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController

  before_filter :authenticate_user, :except => [:new, :create]
  
  def new
    @physician = Physician.new
    @no_session_format = true
    session[:physician_id] = nil
    session[:patient_id] = nil 
  end

  def create
    @physician = Physician.new(params[:physician])
    if @physician.save
      redirect_to matched_path(params[:physician])
      return false
    else
      render 'new'
      return false
    end
  end


  def physician_account
    if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
      if (session[:physician_id] == 1)
        @admin_ph = true
        @ph = Physician.find(params[:physician_id])
      elsif ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s))
        @normal_ph = true
        @ph = Physician.find(params[:physician_id])
      end
    else
      patient_restriction
    end
  end

  def edit_physician_account
    if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
      if (session[:physician_id] == 1)
        @admin_ph = true
        @ph = Physician.find(params[:physician_id])
      elsif ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s))
        @normal_ph = true
        @ph = Physician.find(params[:physician_id])
      end
    else
      patient_restriction
    end
  end

    # if (session[:physician_id].to_s && (params[:physician_id] == session[:physician_id].to_s)) || (session[:physician_id] == 1)
    #   if session[:physician_id] == 1
    #     @ph = Physician.find(params[:id])
    #   else
    #     @ph = Physician.find(params[:physician_id])
    #   end
    #   if (@ph.update_attributes(params[:physician]))
    #     redirect_to physician_account_path(:physician_id => @ph.id), :notice => "Your updates were successful."
    #     return false
    #   else
    #     redirect_to :action => 'edit_physician_account'
    #     return false
    #   end

  def update
    if (session[:physician_id].to_s && (params[:id] == session[:physician_id].to_s)) || (session[:physician_id] == 1)
      @ph = Physician.find(params[:id])
      if @ph.first_name == nil
        @ph.update_attributes(params[:physician])
        redirect_to welcome_ph_instructions_path(:physician_id => @ph.id)
        return false
      elsif @ph.first_name
        if @ph.update_attributes(params[:physician])
          redirect_to physician_account_path(:physician_id => @ph.id), :notice => "Your updates were successful."
          return false
        else
          redirect_to :action => 'edit_physician_account'
          return false
        end
      else
        redirect_to :action => 'physician_additional_information'
        return false
      end
    else
      patient_restriction
    end
  end

  def ph_password_edit
    if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
      @ph = Physician.find(params[:physician_id])  
    else
      patient_restriction
    end
  end

  def ph_password_update
    if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
        @ph = Physician.find(params[:physician_id])
      if (@ph.update_attributes(params[:physician]))
        redirect_to physician_patients_path(:physician_id => @ph.id), :notice => "Your password update was successful."
        return false
      else
        redirect_to :action => 'ph_password_edit'
        return false
      end
    else
      patient_restriction
    end
  end


  def deactivate_pt_message
    @ph = Physician.find(params[:physician_id])
    @pt = Patient.find(params[:patient_id])
  end
  
  def deactivate_ph_message
    @ph = Physician.find(params[:physician_id])
  end
  
  def signup_part2
    @ph = Physician.find(params[:id])
    @ph.attributes = params[:physician]
    if @ph.save
      redirect_to welcome_ph_instructions_path(:physician_id => @ph.id), :notice => "Your information saved."
      return false
    else
      redirect_to :action => 'physician_additional_information'
      return false
    end
  end

  def physician_additional_info
    if (session[:physician_id].to_s && (params[:id] == session[:physician_id].to_s)) || (session[:physician_id] == 1)
      @ph = Physician.find(params[:id])
    else
      patient_restriction
    end
  end
  
  def welcome_ph_instructions
    @ph = Physician.find(params[:physician_id])
  end
  
  def unarchive_patient
    if ((session[:physician_id]).to_s && ((params[:id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
    @pt = Patient.find(params[:patient_id])
    @ph = Physician.find(@pt.physician_id)
    @pt.archive = nil
    @pt.save(:validate => false)
    redirect_to physician_patients_path(@ph, @pt)
    return false
    else
      patient_restriction
    end
    
  end
  
  
def pt_archive_index
  @ph = Physician.find(params[:physician_id])
  @pt_arch = @ph.patients.where(:archive => true).all
end

end

app/views/physicians/edit.html.erb
<%= form_for @ph, :url => { :action => "update" }, :html => {:class => "form-horizontal", :method => "put" } do |f| %>
  <legend>Patient</legend>
  <% if @ph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ph.errors.count, "error") %> prohibited your changes from being saved:</h2>

      <ul>
      <% @ph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="control-group">
    <%= f.label :first_name, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :first_name %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :last_name, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :last_name %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :state, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :state %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :medical_specialty, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :speciatly %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :email, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :email %>
    </div>
  </div>

	

  <div class="form-actions">
		<%= f.button "Save Changes", :class => "btn btn-primary" %>
    <%= link_to physician_path(@ph) do %>
      <button class="btn" method="get">Go Back</button>
    <% end %>
  </div>

<% end %>

app/views/physicians/edit_physician_account.html.erb
<%= form_for @ph, :validate => true, :html => {:class => "form-horizontal"} do |f| %>
  <legend>Edit Account</legend>
  <% if @ph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ph.errors.count, "error") %> prohibited your changes from being saved:</h2>

      <ul>
      <% @ph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="control-group">
    <%= f.label :first_name, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :first_name %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :last_name, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :last_name %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :state, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :state %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :medical_specialty, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :specialty %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :email_for_login, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :email %>
    </div>
  </div>

	

  <div class="form-actions">
		<%= f.button "Save Changes", :class => "btn btn-primary" %>
    <%= link_to physician_account_path(:physician_id => @ph.id) do %>
      <button class="btn" method="get">Go Back</button>
    <% end %>
  </div>

<% end %>

app/views/physicians/new.html.erb
<h1>Physician Sign Up</h1>

<%= form_for @physician, :validate => true do |f| %>
  
    <% if @physician.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited your changes from being saved:</h2>

	      <ul>
	      <% @physician.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
  
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/physicians/ph_password_edit.html.erb
<%= form_for @ph, :url => ph_password_update_path(:physician_id => @ph.id), :validate => true, :html => {:class => "form-horizontal"} do |f| %>
  <legend>New Password</legend>
	<% if @ph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ph.errors.count, "error") %> prohibited your changes from being saved:</h2>

      <ul>
      <% @ph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	
	<div class="control-group">
    <%= f.label :new_password, :class => "control-label" %>
    <div class= "controls">
      <%= f.password_field :password %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :new_password_confirmation, :class => "control-label" %>
    <div class= "controls">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="form-actions">
		<%= f.button "Save Changes", :class => "btn btn-primary" %>
    <%= link_to physician_account_path(:physician_id => @ph.id) do %>
      <button class="btn" method="get">Cancel</button>
    <% end %>
  </div>

<% end %>

app/views/physicians/physician_account.html.erb
<h2>Physician Details</h2>
<br />
<table class="table table-bordered table-striped">
  <tr><th>First Name</th><td><%= @ph.first_name  %></td></tr>
  <tr><th>Last Name</th><td><%= @ph.last_name %></td></tr>
  <tr><th>Email</th><td><%= @ph.email %></td></tr>
  <tr><th>State</th><td><%= @ph.state %></td></tr>
  <tr><th>Medical Specialty</th><td><%= @ph.specialty %></td></tr>
</table>

<div class="form-actions">
  <%= link_to physician_patients_path(@ph) do %>
    <button class="btn">&lt;&lt; Return to Patients Listing</button>
  <% end %>
  <%= link_to edit_physician_account_path(:physician_id => @ph.id)  do %>
    <button class="btn btn-warning">Edit</button>
  <% end %>
	<%= link_to ph_password_edit_path(:physician_id => @ph.id)  do %>
     <button class="btn btn-warning">Change Password</button>
  <% end %>

     
</div>
<% if @normal_ph %>
<%= link_to "Deactivate Account", deactivate_ph_message_path(:physician_id => @ph.id), confirm: 'Are you sure you want to deactivate your account?'%>
<% end %>

app/views/physicians/physician_additional_info.html.erb
<h1>Please Provide A Few More Details...</h1>

<%= form_for @ph, :validate => true, 
                  :method => :put, 
                  :url => physician_signup_part2_path(:id => @ph.id), 
                  :html => {:class => "form-horizontal" } do |f| %>
  <legend>Physician</legend>
  <% if @ph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ph.errors.count, "error") %> prohibited your changes from being saved:</h2>

      <ul>
      <% @ph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="control-group">
    <%= f.label :first_name, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :first_name %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :last_name, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :last_name %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :state, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :state %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :medical_specialty, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :specialty %>
    </div>
  </div>

  <div class="form-actions">
		<%= f.button "Continue", :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/physicians/pt_archive_index.html.erb
     ||     <%= link_to "Back to Patients Listing", physician_patients_path(@ph) %>

<h2>Archived Patient Accounts</h2>

<% @pt_arch.each do |pt| %>
	</br> <%= pt.last_name_first %> <%= pt.phone_number %> Account Status: <%= pt.billing_status %>
	
	<%= link_to "Unarchive", unarchive_patient_path(:patient_id => pt.id, :id => @ph.id) %>
	
	</br>
	<% end %>

app/views/physicians/welcome_ph_instructions.html.erb
</br></br></br>Welcome! Before beginning treatment with a patient, sign them up by clicking the "Create New Patient" Button. Once they are signed up, they will appear in your list of patients, and the patient can begin recording log entries via text messages. 

</br></br></br><%= link_to "Begin!", physician_patients_path(@ph) %></br></br></br>