config/routes.rb
Bulimia::Application.routes.draw do
  
  root :to => 'application#home_page'
  
  resources :physicians do
    resources :patients do
      resources :log_entries
    end
  end
  
  match 'physician_signup_part2/:id(.:format)' => 'physicians#signup_part2', :as => "physician_signup_part2"
  match "home_page" => "application#home_page", :as => "home_page"
  match "deactivate_pt_msg/:physician_id/:patient_id" => "physicians#deactivate_pt_message", :as => "deactivate_pt_message"
  match "deactivate_ph_msg/:physician_id" => "physicians#deactivate_ph_message", :as => "deactivate_ph_message"
  match "ph_deactivate" => "physicians#destroy_archive", :as => "destroy_archive"
  match "pt_archive/:physician_id/:id" => "patients#archive", :as => "archive_pt"
  match "physician/:physician_id/patient_archive" => "physicians#pt_archive_index", :as => "pt_archive_index"
  match "code" => "sessions#new_patient_code_verification", :as => "patient_code"
  match "new_patient" => "sessions#new_patient_start_code_entry", :as => "new_patient_start_code_entry"
  match "new_patient_password_setup/:pt_id" => "sessions#new_patient_password_setup", :as => "new_patient_password_setup"
  match "p_set/:pt_id" => "sessions#password_set", :as => "password_set"
  
  
  
  match 'phone/sms_handler' => "phone#sms_handler", :as => "sms_handler"
  match 'after_start_code_web_handler' => "patients#after_start_code_web_handler", :as => "after_start_code_web_handler"
  
  match "physician_log_out" => "sessions#destroy_ph", :as => "log_out"
  match "physician_log_in" => "sessions#new_physician_session", :as => "log_in"
  match "physician_find" => "sessions#create_ph_session", :as => "matched"
  match "physician_sign_up" => "physicians#new", :as => "sign_up"
  match "physician_additional_info" => "physicians#physician_additional_info", :as => "physician_additional_info"
  match "welcome_ph_instructions/:physician_id" => "physicians#welcome_ph_instructions", :as => "welcome_ph_instructions" 
  match "unarch_pt/:id/:patient_id" => "physicians#unarchive_patient", :as => "unarchive_patient"
  match "physician_account/:physician_id" => "physicians#physician_account", :as => "physician_account"
  match "edit_physician_account/:physician_id" => "physicians#edit_physician_account", :as => "edit_physician_account"
  match "physician_pswd_edit/:physician_id" => "physicians#ph_password_edit", :as => 'ph_password_edit'
  match "physician_pswd_update/:physician_id" => "physicians#ph_password_update", :as => 'ph_password_update'
  
  
  match "patient_log_out" => "sessions#destroy_pt", :as => "patient_log_out"
  match "patient_log_in" => "sessions#new_patient_session", :as => "patient_log_in"
  match "patient_find" => "sessions#create_pt_session", :as => "patient_matched"
  match "patient_edit/:patient_id" => "patients#patient_edit_limited", :as => "pt_edit"
  match "patient_show/:patient_id" => "patients#patient_show_limited", :as => "pt_show"
  match "patient_update/:patient_id" => "patients#patient_update_limited", :as => "pt_update"
  match "patient_welcome/:patient_id" => "patients#patient_welcome", :as => "patient_welcome"
  
  
  match "admin_override_pt_password_edit/:patient_id" => "patients#admin_pt_password_edit", :as => "admin_pt_pass_edit"
  match "admin_override_pt_password_update/:patient_id" => "patients#admin_pt_password_update", :as => "admin_pt_pass_update"
  match "admin" => "admin#index", :as => "admin"
  match "archived_physicians" => "admin#archived_physicians", :as => "archived_physicians"
  match "archived_patients" => "admin#archived_patients", :as => "archived_patients"
  match "active_patients" => "admin#active_patients", :as => "active_patients"
  match "deact_and_arch_pt/:patient_id" => "admin#deactivate_and_archive_patient", :as => "deactivate_and_archive_patient"
  match "react_and_unarch_pt/:patient_id" => "admin#reactivate_and_unarchive_patient", :as => "reactivate_and_unarchive_patient"
  match "archive_a_physician/:physician_id" => "admin#archive_a_physician", :as => "archive_a_physician"
  match "unarchive_a_physician/:physician_id" => "admin#unarchive_a_physician", :as => "unarchive_a_physician"
  

    
  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :phone_number, :password, :password_confirmation, :first_name, :last_name, :dob, :sex, :diagnosis, :archive
  has_secure_password
  validates_presence_of :password, :on => :create
  
  validates_presence_of :first_name, :last_name
  validates_presence_of :password, :on => :create
  validates_length_of :password, :minimum => 6, :allow_blank => false, :on => :create
  validates_confirmation_of :password, :on => :create 
  validates_presence_of :phone_number, :length => { :is => 10 }
  validates_presence_of :phone_number, :format => { :with => /^\d{10}$/, :message => "Must be 10 digits and contain no parathesis or dashes" }
  validates_uniqueness_of :phone_number
  validates_presence_of :sex, :on => :create
  validates_presence_of :dob, :on => :create, :format => { :with => /^(0[1-9]{1}|[12]{1}[0-9]{1}|3[01]{1}).{1}(0[1-9]{1}|1[0-2]{1}).{1}([12]{1}[0-9]{3})$/, :message => "MM-DD-YYYY format required" }
  validates_presence_of :diagnosis, :on => :create
  
  has_many :log_entries
  has_one :convo_handler
  has_one :physician

  def base_date
    unless @base_date
      @base_date = self.log_entries.first.created_at.change(:hour => 8)
    end
  end

  def determine_log_entry_day_index(log_entry)
    return (self.base_date - log_entry.date.change(:hour => 8)).to_i + 1
  end

  def last_name_first
    if self.first_name && self.last_name
      self.last_name + ", " + self.first_name
    end
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_filter :authenticate_user

  def index
    if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
      @ph = Physician.find(params[:physician_id])
      @pt = @ph.patients.where(:archive => nil).all
      @patients = @pt.sort_by { |pt| pt.last_name.downcase }
      @physician_or_admin_view = true
    else
      patient_restriction
    end
  end
  
  def archive
    if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
      @ph = Physician.find(params[:physician_id])
      @patient = Patient.find(params[:id])
      @patient.activity_history = @patient.activity_history + "  >>>>>> Archived by #{@ph.email} on #{DateTime.now.to_time.strftime('%c')}"
      @patient.archive = true
      @patient.phone_number = ""
      if @patient.save(:validate => false)
        redirect_to pt_archive_index_path(:physician_id => @ph.id)
        return false
      else
        redirect_to physician_patients_path(@ph)
        return false
      end
    else
      patient_restriction
    end
  end
  
  def index_pt_archive
    if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
      @ph = Physician.find(params[:physician_id])
      @pt = @ph.patients.where(:archive => true).all
      @patients = @pt.sort_by { |pt| pt.last_name.downcase }
    else
      patient_restriction
    end
  end

    def show
      if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
        @ph = Physician.find(params[:physician_id])
        @patient = Patient.find(params[:id])
      else
        patient_restriction
      end
    end

    def new
      if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
        @ph = Physician.find(params[:physician_id])
        @patient = @ph.patients.build
      else
        patient_restriction
      end
    end

    def edit
      if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
        @patient = Patient.find(params[:id])
        @ph = Physician.find(params[:physician_id])
      else
        patient_restriction
      end
    end

    def create
      if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
        @ph = Physician.find(params[:physician_id])
        @patient = @ph.patients.build(params[:patient])
        @patient.activity_history = "*****Account created by #{@ph.email} on #{DateTime.now.to_time.strftime('%c')}"
        @patient.signup_status = "new"
        @patient.start_code = rand(999999).to_s.center(6, rand(9).to_s)
        @password_random_suffix = rand(999999).to_s.center(6, rand(9).to_s)
        if @patient.save
          session[:patient_start] = @patient.id
          redirect_to sms_handler_path
          return false
        else
          render :action => "new"
          return false
        end
      else
        patient_restriction
      end
    end
  

    def update
      if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
        @ph = Physician.find(params[:physician_id])
        @patient = Patient.find(params[:id])
        @patient.signup_status = "returning"
        @patient.save(:validate => false)

        if @patient.update_attributes(params[:patient])
          redirect_to physician_patient_path
          return false
        else
          render :action =>"edit"
          return false
        end
      else
        patient_restriction
      end
    end


    def destroy
      if ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s)) || (session[:physician_id] == 1)
        @patient = Patient.find(params[:id])
        @ph = Physician.find(params[:physician_id])
        @patient.destroy
        redirect_to physician_patients_url(@ph)
        return false
      else
        patient_restriction
      end
    end
    
    def admin_pt_password_edit
      if session[:physician_id] == 1
        @patient = Patient.find(params[:patient_id])
        @ph = Physician.find(@patient.physician_id)  
      else
        redirect_to home_page_path
        return false
      end
    end
    
    def admin_pt_password_update
      if session[:physician_id] == 1
        @patient = Patient.find(params[:patient_id])
        @ph = Physician.find(@patient.physician_id)
        @patient.signup_status = "returning"
        @patient.save(:validate => false)
        
        if @patient.update_attributes(params[:patient])
          redirect_to physician_patient_path(@ph, @patient), :notice => "The patient's password was successfully reset"
          return false
        else
          render :action =>"admin_pt_password_edit"
          return false
        end
      else
        redirect_to home_page_path
        return false
      end
    end
    
    def patient_welcome
      @pt = Patient.find(params[:patient_id])
      @ph = Physician.find(@pt.physician_id)
    end
    

    ############# paitent-specific methods #######

    def patient_edit_limited
      if (session[:patient_id]).to_s && (params[:patient_id] == (session[:patient_id]).to_s)
        @patient = Patient.find(params[:patient_id])
        @ph = Physician.find(@patient.physician_id)
      else
        physician_restriction
      end
    end

    def patient_show_limited
      if (session[:patient_id]).to_s && ((params[:patient_id]) == (session[:patient_id]).to_s)
        @patient = Patient.find(params[:patient_id])
        @ph = Physician.find(@patient.physician_id)
      else
        physician_restriction
      end
    end

    def patient_update_limited
      if (session[:patient_id]).to_s && ((params[:patient_id]) == (session[:patient_id]).to_s)
        @patient = Patient.find(params[:patient_id])
        @ph = Physician.find(@patient.physician_id)
        @patient.signup_status = "returning"
        @patient.save(:validate => false)
        if @patient.update_attributes(params[:patient])
          redirect_to pt_show_path(params[:patient_id])
          return false
        else
          render :action => "patient_edit_limited"
          return false
        end
      else
        patient_restriction
      end
    end
    


  end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for [@ph, @patient], :html => {:class => "form-horizontal" } do |f| %>
<legend><%= mode == :edit ? "Edit Account" : "New Patient" %> Patient</legend>
<% if @patient.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

	<ul>
		<% @patient.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="control-group">
	<%= f.label :first_name, :class => "control-label" %>
	<div class= "controls">
		<%= f.text_field :first_name %>
	</div>
</div>

<div class="control-group">
	<%= f.label :last_name, :class => "control-label" %>
	<div class= "controls">
		<%= f.text_field :last_name  %>
	</div>
</div>

<div class="control-group">
	<%= f.label :dob, :class => "control-label" %>
	<div class= "controls">
		<%= f.text_field :dob %>
	</div>
</div>

<div class="control-group">
	<%= f.label :sex, :class => "control-label" %>
	<div class= "controls">
		<%= f.text_field :sex %>
	</div>
</div>

<div class="control-group">
	<%= f.label :diagnosis, :class => "control-label" %>
	<div class= "controls">
		<%= f.text_field :diagnosis %>
	</div>
</div>

<div class="control-group">
	<%= f.label :phone_number, :class => "control-label" %>
	<div class= "controls">
		<%= f.text_field :phone_number %>
	</div>
</div>

<% if mode == :new %>
<%= f.hidden_field :password, :value => "1234bulimiatx#{@password_random_suffix}"%>
<%= f.hidden_field :password_confirmation, :value => "1234bulimiatx#{@password_random_suffix}" %>
<% end %>

<div class="form-actions">
	<% mode == :edit ? button_text = "Save Changes to Patient" : button_text = "Save Patient" %>
	<%= f.button button_text, :class => "btn btn-primary" %>
	<%= link_to physician_patients_path(@ph) do %>
	<button class="btn" method="get">Go Back</button>
	<% end %>
</div>

<% end %>

app/views/patients/admin_pt_password_edit.html.erb
<%= form_for @patient, :url => { :action => "admin_pt_password_update" }, :html => {:class => "form-horizontal", :method => "put" } do |f| %>
<legend>Patient</legend>
<% if @patient.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@patient.errors.count, "error") %> prohibited the password change from being saved:</h2>

	<ul>
		<% @patient.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>


<div class="control-group">
	<%= f.label :new_password, :class => "control-label" %>
	<div class= "controls">
		<%= f.password_field :password %>
	</div>
</div>

<div class="control-group">
	<%= f.label :new_password_confirmation, :class => "control-label" %>
	<div class= "controls">
		<%= f.password_field :password_confirmation %>
	</div>
</div>

<div class="form-actions">
	<%= f.button "Save Changes", :class => "btn btn-primary" %>
	<%= link_to physician_patient_path(@ph, @patient) do %>
	<button class="btn" method="get">Go Back</button>
	<% end %>
</div>

<% end %>

app/views/patients/edit.html.erb
<%= render 'form', :mode => :edit %>

app/views/patients/index.html.erb
<h2>Listing Patients</h2> <h2>of Dr. <% if @physician_or_admin_view && @ph.first_name && @ph.last_name%> <%= @ph.first_name + " " + @ph.last_name %> <% end %></h2>  <% if @ph.archive == true %> <h2>WITHOUT WEB/SMS ACCESS</h2> <% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Dob</th>
      <th>Sex</th>
      <th>Diagnosis</th>
  	  <th>Phone Number</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
			<th></th>
	    <th></th>
    </tr>
  </thead>
<tbody>
  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.first_name %></td>
      <td><%= patient.last_name %></td>
      <td><%= patient.dob %></td>
      <td><%= patient.sex %></td>
      <td><%= patient.diagnosis %></td>
    	<td><%= patient.phone_number %></td>
      <td>    
        <%= link_to physician_patient_path(@ph, patient) do %>
          <button class="btn">View Patient</button>
        <% end %>
      </td>
			<td>
        <%= link_to physician_patient_log_entries_path(@ph, patient) do %>
          <button class="btn btn-info">View Log</button>
        <% end %>
      </td>
      <td>
        <%= link_to edit_physician_patient_path(@ph, patient) do %>
          <button class="btn btn-warning">Edit Patient</button>
        <% end %>
      </td>
      <td>
        <%= link_to archive_pt_path(:physician_id => @ph.id, :id => patient.id), confirm: 'Are you sure you want to archive this patient?' do %>
          <button class="btn btn-danger">Archive Patient</button>
        <% end %>
      </td>
			<td>
        <%= link_to deactivate_pt_message_path(:physician_id => @ph.id, :patient_id => patient.id), confirm: 'Are you sure you want to deactivate this patient\'s account?' do %>
          <button class="btn btn-danger">Cancel Account</button>
        <% end %>
      </td>
    <% if session[:physician_id] == 1 %>
    <td>
			<%= link_to physician_patient_path(@ph, patient), confirm: 'Are you sure you want to delete this patient?', method: :delete do %>
        <button class="btn btn-danger">Delete Patient</button>
      <% end %>
    </td>
    <% end %>
      
    </tr>
  <% end %>
</tbody>
</table>

<div class="form-actions">
    <%= link_to new_physician_patient_path do %>
        <button class="btn">Create New Patient</button>
    <% end %>
		<%= link_to pt_archive_index_path(:physician_id => @ph.id) do %>
        <button class="btn">View Patient Archive</button>
    <% end %>
		<%= link_to physician_account_path(:physician_id => @ph.id) do %>
        <button class="btn">Manage Account</button>
    <% end %>
</div>

app/views/patients/new.html.erb
<%= render 'form', :mode => :new %>

app/views/patients/patient_edit_limited.html.erb
<%= form_for [@ph, @patient], :url => { :action => "patient_update_limited" }, :html => {:class => "form-horizontal", :method => "put" } do |f| %>
  <legend>Patient</legend>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited your changes from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="control-group">
    <%= f.label :phone_number, :class => "control-label" %>
    <div class= "controls">
      <%= f.text_field :phone_number %>
    </div>
  </div>
	
	<div class="control-group">
    <%= f.label :new_password, :class => "control-label" %>
    <div class= "controls">
      <%= f.password_field :password %>
    </div>
  </div>

	<div class="control-group">
    <%= f.label :new_password_confirmation, :class => "control-label" %>
    <div class= "controls">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="form-actions">
		<%= f.button "Save Changes", :class => "btn btn-primary" %>
    <%= link_to physician_patient_log_entries_path(@ph, @patient) do %>
      <button class="btn" method="get">Cancel</button>
    <% end %>
  </div>

<% end %>

app/views/patients/patient_show_limited.html.erb
<h2>Patient Details</h2>
<br />
<table class="table table-bordered table-striped">
  <tr><th>First Name</th><td><%= @patient.first_name  %></td></tr>
  <tr><th>Last Name</th><td><%= @patient.last_name %></td></tr>
  <tr><th>Date of Birth</th><td><%= @patient.dob %></td></tr>
  <tr><th>Phone Number</th><td><%= @patient.phone_number %></td></tr>
	<tr><th>Password</th><td>Hidden***</td></tr>
</table>

<div class="form-actions">
  <%= link_to physician_patient_log_entries_path(@ph, @patient) do %>
    <button class="btn">&lt;&lt; Back to Log</button>
  <% end %>
</div>


<%= link_to "Deactivate Account", deactivate_pt_message_path(:patient_id => @patient.id, :physician_id => @ph.id), confirm: 'Are you sure you want to deactivate your account?'%>

app/views/patients/patient_welcome.html.erb
</br></br></br>Welcome! Bivola allows you to create diary entries about eating behaviors via text messaging or via the web. Text 'help' to Bivola's number (310)598-2903 for instructions on creating entries via text messaging. </br></br></br>

<%= link_to "Begin!", physician_patient_path(@ph, @pt) %>

app/views/patients/show.html.erb
<h2>Patient Details</h2>
<br />
<table class="table table-bordered table-striped">
  <tr><th>First Name</th><td><%= @patient.first_name  %></td></tr>
  <tr><th>Last Name</th><td><%= @patient.last_name %></td></tr>
  <tr><th>Date of Birth</th><td><%= @patient.dob %></td></tr>
  <tr><th>Sex</th><td><%= @patient.sex %></tr>
  <tr><th>Diagnosis</th><td><%= @patient.diagnosis %></tr>
  <tr><th>Phone Number</th><td><%= @patient.phone_number %></td></tr>
</table>

<div class="form-actions">
  <%= link_to physician_patients_path(@ph) do %>
    <button class="btn">&lt;&lt; Return to Patients Listing</button>
  <% end %>
  <%= link_to edit_physician_patient_path(@ph, @patient)  do %>
    <button class="btn btn-warning">Edit this Patient</button>
  <% end %>
	<% if session[:physician_id] == 1 %>
		<%= link_to admin_pt_pass_edit_path(:patient_id => @patient.id)  do %>
	    <button class="btn btn-danger">Reset Password</button>
	  <% end %>
	<% end %>
  <%= link_to archive_pt_path(:physician_id => @ph.id, :id => @patient.id), confirm: 'Are you sure?' do %>
    <button class="btn btn-danger">Archive Patient</button>
  <% end %>
</div>
<%= link_to "Deactivate Patient Account", deactivate_pt_message_path(:patient_id => @patient.id, :physician_id => @ph.id), confirm: 'Are you sure you want to deactivate this patient account?'%>