config/routes.rb
Bulimia::Application.routes.draw do
  
  root :to => 'application#home_page'
  
  resources :physicians do
    resources :patients do
      resources :log_entries
    end
  end
  
  match 'physician_signup_part2/:id(.:format)' => 'physicians#signup_part2', :as => "physician_signup_part2"
  match "home_page" => "application#home_page", :as => "home_page"
  match "deactivate_pt_msg/:physician_id/:patient_id" => "physicians#deactivate_pt_message", :as => "deactivate_pt_message"
  match "deactivate_ph_msg/:physician_id" => "physicians#deactivate_ph_message", :as => "deactivate_ph_message"
  match "ph_deactivate" => "physicians#destroy_archive", :as => "destroy_archive"
  match "pt_archive/:physician_id/:id" => "patients#archive", :as => "archive_pt"
  match "physician/:physician_id/patient_archive" => "physicians#pt_archive_index", :as => "pt_archive_index"
  match "code" => "sessions#new_patient_code_verification", :as => "patient_code"
  match "new_patient" => "sessions#new_patient_start_code_entry", :as => "new_patient_start_code_entry"
  match "new_patient_password_setup/:pt_id" => "sessions#new_patient_password_setup", :as => "new_patient_password_setup"
  match "p_set/:pt_id" => "sessions#password_set", :as => "password_set"
  
  
  
  match 'phone/sms_handler' => "phone#sms_handler", :as => "sms_handler"
  match 'after_start_code_web_handler' => "patients#after_start_code_web_handler", :as => "after_start_code_web_handler"
  
  match "physician_log_out" => "sessions#destroy_ph", :as => "log_out"
  match "physician_log_in" => "sessions#new_physician_session", :as => "log_in"
  match "physician_find" => "sessions#create_ph_session", :as => "matched"
  match "physician_sign_up" => "physicians#new", :as => "sign_up"
  match "physician_additional_info" => "physicians#physician_additional_info", :as => "physician_additional_info"
  match "welcome_ph_instructions/:physician_id" => "physicians#welcome_ph_instructions", :as => "welcome_ph_instructions" 
  match "unarch_pt/:id/:patient_id" => "physicians#unarchive_patient", :as => "unarchive_patient"
  match "physician_account/:physician_id" => "physicians#physician_account", :as => "physician_account"
  match "edit_physician_account/:physician_id" => "physicians#edit_physician_account", :as => "edit_physician_account"
  match "physician_pswd_edit/:physician_id" => "physicians#ph_password_edit", :as => 'ph_password_edit'
  match "physician_pswd_update/:physician_id" => "physicians#ph_password_update", :as => 'ph_password_update'
  
  
  match "patient_log_out" => "sessions#destroy_pt", :as => "patient_log_out"
  match "patient_log_in" => "sessions#new_patient_session", :as => "patient_log_in"
  match "patient_find" => "sessions#create_pt_session", :as => "patient_matched"
  match "patient_edit/:patient_id" => "patients#patient_edit_limited", :as => "pt_edit"
  match "patient_show/:patient_id" => "patients#patient_show_limited", :as => "pt_show"
  match "patient_update/:patient_id" => "patients#patient_update_limited", :as => "pt_update"
  match "patient_welcome/:patient_id" => "patients#patient_welcome", :as => "patient_welcome"
  
  
  match "admin_override_pt_password_edit/:patient_id" => "patients#admin_pt_password_edit", :as => "admin_pt_pass_edit"
  match "admin_override_pt_password_update/:patient_id" => "patients#admin_pt_password_update", :as => "admin_pt_pass_update"
  match "admin" => "admin#index", :as => "admin"
  match "archived_physicians" => "admin#archived_physicians", :as => "archived_physicians"
  match "archived_patients" => "admin#archived_patients", :as => "archived_patients"
  match "active_patients" => "admin#active_patients", :as => "active_patients"
  match "deact_and_arch_pt/:patient_id" => "admin#deactivate_and_archive_patient", :as => "deactivate_and_archive_patient"
  match "react_and_unarch_pt/:patient_id" => "admin#reactivate_and_unarchive_patient", :as => "reactivate_and_unarchive_patient"
  match "archive_a_physician/:physician_id" => "admin#archive_a_physician", :as => "archive_a_physician"
  match "unarchive_a_physician/:physician_id" => "admin#unarchive_a_physician", :as => "unarchive_a_physician"
  

    
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def home_page
    @no_session_format = true
    if session[:physician_id]
      session[:physician_id] = nil
    elsif session[:patient_id]
       session[:patient_id] = nil
    end
  end
  
  
  def patient_restriction
    if session[:patient_id]
      pt_id = session[:patient_id]
      @pt = Patient.find(pt_id)
      @ph = Physician.find(@pt.physician_id)
      redirect_to physician_patient_log_entries_path(@ph, @pt), :notice => "That page has restricted access."
      return false
    else
     redirect_to home_page_path
     return false
    end
  end
 
 def physician_restriction
  if session[:physician_id]
    ph_id = session[:physician_id]
    @ph = Physician.find(ph_id)
    redirect_to physician_patient_log_entries_path(@ph), :notice => "That page has restricted access."
    return false
  else
    redirect_to home_page_path
    return false
  end
end
  
  private

  def current_physician
    @current_physician ||= Physician.find(session[:physician_id]) if session[:physician_id]
  end
  
  def authenticate_user
    if session[:physician_id] || session[:patient_id]
    else
      redirect_to home_page_path
      return false
    end
  end
  
  def authenticate_admin
    if session[:physician_id] == 1
    else
      redirect_to home_page_path
      return false
    end
  end
  
  def restrict_access_to_relevant_pages
      if ((session[:patient_id]).to_s && ((params[:patient_id]) == (session[:patient_id]).to_s)) || ((session[:physician_id]).to_s && ((params[:physician_id]) == (session[:physician_id]).to_s))
      elsif session[:physician_id] == 1
      else
        redirect_to home_page_path
        return false
      end
  end
  
  def current_patient
    @current_patient ||= Patient.find(session[:patient_id]) if session[:patient_id]
  end
  
  
  helper_method :current_physician
  helper_method :current_patient
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  
  
  
end

app/views/application/deactivate_message.html.erb
<p>Please send an email to cancel@bivola.com indicating that you would like to cancel this account. Within 72 hours, this account will be deactivated and all billing associated with this account will cease. All patient data associated with this account will be sent to you electronically via email. The information will be accessible with your Bivola password. Once this data is released to you, Bivola does not take responsibility for the security of these data and does not guarantee that a copy of these data will remain saved in Bivola's system. Whether you were satisfied or dissatisfied with Bivola, we would appreciate your feedback. We are always looking to make improvements to our product. Thank you for using Bivola.</p>

<% if session[:patient_id] %>
<%= link_to "Go Back", pt_show_path(:patient_id => @pt.id) %>
<% elsif session[:physician_id] %>
<%= link_to "Go Back", physician_patient_path(@ph, @pt) %>
<% end %>

app/views/application/deactivate_ph_message.html.erb
<p>Please send an email to cancel@bivola.com indicating that you would like to cancel this account. Within 72 hours, this account will be deactivated and all billing associated with this account will cease. All patient data associated with this account will be sent to you electronically via email. The information will be accessible with your Bivola password. Once this data is released to you, Bivola does not take responsibility for the security of these data and does not guarantee that a copy of these data will remain saved in Bivola's system. Whether you were satisfied or dissatisfied with Bivola, we would appreciate your feedback. We are always looking to make improvements to our product. Thank you for using Bivola.</p>

<%= link_to "OK", physician_patients_path(@ph) %>

app/views/application/deactivate_pt_message.html.erb
<p>Please send an email to cancel@bivola.com indicating that you would like to cancel this account. Within 72 hours, this account will be deactivated and all billing associated with this account will cease. All patient data associated with this account will be sent to both doctor and patient electronically via email. The information will be accessible with your Bivola password. Once this data is released to you, Bivola does not take responsibility for the security of these data and does not guarantee that a copy of these data will remain saved in Bivola's system. Whether you were satisfied or dissatisfied with Bivola, we would appreciate your feedback. We are always looking to make improvements to our product. Thank you for using Bivola.</p>

<% if session[:patient_id] %>
<%= link_to "OK", pt_show_path(:patient_id => @pt.id) %>
<% elsif session[:physician_id] %>
<%= link_to "OK", physician_patient_path(@ph, @pt) %>
<% end %>

app/views/application/home_page.html.erb
</br></br><h3>HOME PAGE</h3></br></br>
<div>
<h1>Physicians</h1></br>
<h2><%= link_to "Sign Up", sign_up_path %>  ||  <%= link_to "Log In", log_in_path %></h2>
</div>


</br></br></br></br>___________________________________</br></br></br></br>
<div>
<h1>Patients</h1></br>
<h2><%= link_to "New Patient Log In", new_patient_start_code_entry_path %>  ||  <%= link_to "Log In", patient_log_in_path %></h2>
</div>